### ISSUE TITLE
Really Nice Control. But something wrong after clicking the done button

### ISSUE THREAD

**Issue by BitterSymphony** [BradleyDHobbs/Xamarin.CropView#2]
It thrown this exception after clicking the done button (after cropping the image)

Foundation.MonoTouchException: Objective-C exception thrown. Name: NSInvalidArgumentException Reason:
[UIImage croppedImageWithFrame:angle:]: unrecognized selector sent to instance 0x165c6dd0

Could you take a look at this? Thanks a lot

**Comment by BradleyDHobbs** [comment]
Sorry, forgot to update the readme in master branch. 

Please take a look at the updated readme in regards to LinkerFlags.

**Comment by BitterSymphony** [comment]
Yayyy. Its working now. Thank you so much for your help and quick response :).
